import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from './index.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className={styles.square}>
          <h1>HOMEPAGE</h1>
        </div>

        {/* Sections */}
        <SectionAlmaas />

      </main>
    </>
  )
}


/**
 * TODO
 * buat section baru kemudian tampilkan di homepage
 */

function SectionAlmaas () {
  return(
    <section className={styles.sectionAlmaas}>
      <h1>Hello World - Almaas</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero repudiandae dicta eum. Maxime quis expedita totam. Minima tempora unde pariatur eligendi, asperiores laboriosam vel nemo alias earum recusandae dolor culpa.</p>
      <Link className={styles.linkAlmaas} href="/almaas">My Page {'>'}</Link>
    </section>
  )
}
